// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA14YrexcMteujwJ4XuGee0rOFvWzAGc7s',
    appId: '1:645408821072:web:dabc590a0f9d2d6a312655',
    messagingSenderId: '645408821072',
    projectId: 'instagram-7dc7a',
    authDomain: 'instagram-7dc7a.firebaseapp.com',
    storageBucket: 'instagram-7dc7a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtd3B_tj9tZVtjZSsfrTtjjo9EK3g1R3o',
    appId: '1:645408821072:android:908adc9bd4fb58df312655',
    messagingSenderId: '645408821072',
    projectId: 'instagram-7dc7a',
    storageBucket: 'instagram-7dc7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1GFw7SrPPHS0pUqnOSnVq3L5bxLoCFFs',
    appId: '1:645408821072:ios:020bde6339357605312655',
    messagingSenderId: '645408821072',
    projectId: 'instagram-7dc7a',
    storageBucket: 'instagram-7dc7a.appspot.com',
    iosClientId: '645408821072-5s6ggifsfjtk0h8c1nujue4k2o6g37cm.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1GFw7SrPPHS0pUqnOSnVq3L5bxLoCFFs',
    appId: '1:645408821072:ios:c4ef6297aa538733312655',
    messagingSenderId: '645408821072',
    projectId: 'instagram-7dc7a',
    storageBucket: 'instagram-7dc7a.appspot.com',
    iosClientId: '645408821072-30ufeht0o0hiesscdhkn5rt8debifu79.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram.RunnerTests',
  );
}
